// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// ...

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyBux7jT-KaRaboEuC52rpPYzQ1GRXGRn0g',
      appId: '1:1011356557145:web:59dce4139dcc9ccf207648',
      messagingSenderId: '1011356557145',
      projectId: 'dimash-diploma',
      authDomain: 'dimash-diploma.firebaseapp.com',
      storageBucket: 'dimash-diploma.appspot.com',
      databaseURL:
          'https://dimash-diploma-default-rtdb.asia-southeast1.firebasedatabase.app/');

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC5RvLIi0xT9XCPJMVO_i_8R29a3U4_vA',
    appId: '1:1011356557145:android:deff2485bc325b12207648',
    messagingSenderId: '1011356557145',
    projectId: 'dimash-diploma',
    storageBucket: 'dimash-diploma.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCf10irIF3-Mlz3I1VHQa3GaAryo6Ev_A',
    appId: '1:1011356557145:ios:64388ad3b867a9e4207648',
    messagingSenderId: '1011356557145',
    projectId: 'dimash-diploma',
    storageBucket: 'dimash-diploma.appspot.com',
    iosBundleId: 'com.example.dimashDiploma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCf10irIF3-Mlz3I1VHQa3GaAryo6Ev_A',
    appId: '1:1011356557145:ios:7d80b3f224e5238c207648',
    messagingSenderId: '1011356557145',
    projectId: 'dimash-diploma',
    storageBucket: 'dimash-diploma.appspot.com',
    iosBundleId: 'com.example.dimashDiploma.RunnerTests',
  );
}
