import 'package:dimash_diploma/core/models/symptom.dart';

List<Symptom> symptoms = [
  Symptom(name: 'Кашель'),
  Symptom(name: 'Головная боль'),
  Symptom(name: "Высокая температура"),
  Symptom(name: "Боль в горле"),
  Symptom(name: 'Макрота'),
  Symptom(name: "Покраснение гланд"),
  Symptom(name: "Частое мочеиспускание"),
  Symptom(name: "Сильная жажда"),
  Symptom(name: "Усталость"),
  Symptom(name: "Одышка"),
  Symptom(name: "Свистящее дыхание"),
  Symptom(name: "Затруднение вдоха и выдоха"),
  Symptom(name: "Боль в желудке"),
  Symptom(name: "Тошнота"),
  Symptom(name: "Рвота"),
  Symptom(name: "Односторонняя головная боль"),
  Symptom(name: "Пульсирующая боль"),
  Symptom(name: "Светобоязнь"),
  Symptom(name: "Боль в суставах"),
  Symptom(name: "Отек суставов"),
  Symptom(name: "Ограничение подвижности"),
  Symptom(name: "Пониженное настроение"),
  Symptom(name: "Утренняя тревога"),
  Symptom(name: "Потеря интереса к увлечениям"),
  Symptom(name: "Слабость"),
  Symptom(name: "Бледность кожи"),
  Symptom(name: "Утомляемость"),
  Symptom(name: "Ожог в груди"),
  Symptom(name: "Регургитация"),
  Symptom(name: "Затруднение глотания"),
  Symptom(name: "Боль в спине"),
  Symptom(name: "Ограничение движения"),
  Symptom(name: "Шейная головная боль"),
  Symptom(name: "Боль в верхней части живота"),
  Symptom(name: "Изжога"),
];
